name: Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: install dependencies and check formatting
        run: |
          npm ci
          npm run lint
