name: Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev/new-ui

jobs:
  formatter:
    name: 📝 Formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: install dependencies and check formatting
        run: |
          npm ci
          npm run lint
